/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import { Contract } from 'fuels';
import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Overrides,
  BigNumberish,
  BytesLike,
} from 'fuels';

export type ContractIdInput = { value: string };

export type ContractId = { value: string };

export type TokenListInput = {
  tokens: any;
  cursor: BigNumberish;
  items: BigNumberish;
};

export type TokenList = { tokens: any; cursor: bigint; items: bigint };

interface SwayswapContractAbiInterface extends Interface {
  functions: {
    add_exchange_contract: FunctionFragment;
    get_exchange_contract: FunctionFragment;
    list_contracts: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'add_exchange_contract',
    values: [ContractIdInput, ContractIdInput]
  ): string;
  encodeFunctionData(functionFragment: 'get_exchange_contract', values: [ContractIdInput]): string;
  encodeFunctionData(functionFragment: 'list_contracts', values: [BigNumberish]): string;

  decodeFunctionData(functionFragment: 'add_exchange_contract', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_exchange_contract', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'list_contracts', data: BytesLike): DecodedValue;
}

export class SwayswapContractAbi extends Contract {
  interface: SwayswapContractAbiInterface;
  functions: {
    add_exchange_contract(
      token_id: ContractIdInput,
      exchange_id: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    get_exchange_contract(
      token_id: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractId>;

    list_contracts(
      cursor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TokenList>;
  };

  callStatic: {
    add_exchange_contract(
      token_id: ContractIdInput,
      exchange_id: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    get_exchange_contract(
      token_id: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractId>;

    list_contracts(
      cursor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TokenList>;
  };

  add_exchange_contract(
    token_id: ContractIdInput,
    exchange_id: ContractIdInput,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  get_exchange_contract(
    token_id: ContractIdInput,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractId>;

  list_contracts(
    cursor: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TokenList>;
}
