/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  ContractCall,
  ContractCallOptions,
  Overrides,
  BigNumberish,
  BytesLike,
  CallResult,
  ScriptTransactionRequest,
  TransactionResult,
} from 'fuels';

interface TokenContractStorageSlotsInterface extends Interface {
  functions: {};
}

export class TokenContractStorageSlots extends Contract {
  interface: TokenContractStorageSlotsInterface;
  prepareCall: {};
  submit: {};
  submitResult: {};
  dryRun: {};
  dryRunResult: {};
  simulate: {};
  simulateResult: {};
}
