/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SwayswapContractAbi } from "./SwayswapContractAbi";

export { SwayswapContractAbi__factory } from "./factories/SwayswapContractAbi__factory";
