version: "3"

services:
  test-swayswap-fuel-core:
    env_file:
      - ./fuel-core/.env.docker
    build: ./fuel-core
    ports:
      - "4001:4000"
    volumes:
      - test-swayswap-fuel-core-db:/mnt/test/db
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 10
  test-swayswap-faucet-test:
    env_file:
      - ./fuel-faucet/.env.docker
    environment:
      - FUEL_NODE_URL=http://test-swayswap-fuel-core:4000/graphql
    image: ghcr.io/fuellabs/faucet:v0.1.1
    ports:
      - "4041:4040"
    links:
      - test-swayswap-fuel-core
    depends_on:
      test-swayswap-fuel-core:
        condition: service_healthy
volumes:
  test-swayswap-fuel-core-db:
