/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SwayswapAbi } from "./SwayswapAbi";

export { SwayswapAbi__factory } from "./factories/SwayswapAbi__factory";
