[project]
authors = ["Mohammad"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "master" }
token_abi = { path = "../token_abi" }
