/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  Overrides,
  BigNumberish,
  BytesLike,
} from "fuels";

interface TokenContractAbiInterface extends Interface {
  functions: {
    "mint_coins(u64)": FunctionFragment;
    "burn_coins(u64)": FunctionFragment;
    "force_transfer_coins(u64,struct ContractId,struct ContractId)": FunctionFragment;
    "transfer_coins_to_output(u64,struct ContractId,struct Address)": FunctionFragment;
    "get_balance(struct ContractId,struct ContractId)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mint_coins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burn_coins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "force_transfer_coins",
    values: [BigNumberish, any, any]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer_coins_to_output",
    values: [BigNumberish, any, any]
  ): string;
  encodeFunctionData(
    functionFragment: "get_balance",
    values: [any, any]
  ): string;

  decodeFunctionData(
    functionFragment: "mint_coins",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "burn_coins",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "force_transfer_coins",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "transfer_coins_to_output",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_balance",
    data: BytesLike
  ): DecodedValue;
}

export class TokenContractAbi extends Contract {
  interface: TokenContractAbiInterface;
  functions: {
    mint_coins(
      mint_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    "mint_coins(u64)"(
      mint_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    burn_coins(
      burn_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    "burn_coins(u64)"(
      burn_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    force_transfer_coins(
      coins: BigNumberish,
      asset_id: any,
      target: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    "force_transfer_coins(u64,struct ContractId,struct ContractId)"(
      coins: BigNumberish,
      asset_id: any,
      target: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    transfer_coins_to_output(
      coins: BigNumberish,
      asset_id: any,
      recipient: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    "transfer_coins_to_output(u64,struct ContractId,struct Address)"(
      coins: BigNumberish,
      asset_id: any,
      recipient: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_balance(
      target: any,
      asset_id: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    "get_balance(struct ContractId,struct ContractId)"(
      target: any,
      asset_id: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;
  };

  mint_coins(
    mint_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  "mint_coins(u64)"(
    mint_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  burn_coins(
    burn_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  "burn_coins(u64)"(
    burn_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  force_transfer_coins(
    coins: BigNumberish,
    asset_id: any,
    target: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  "force_transfer_coins(u64,struct ContractId,struct ContractId)"(
    coins: BigNumberish,
    asset_id: any,
    target: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  transfer_coins_to_output(
    coins: BigNumberish,
    asset_id: any,
    recipient: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  "transfer_coins_to_output(u64,struct ContractId,struct Address)"(
    coins: BigNumberish,
    asset_id: any,
    recipient: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  get_balance(
    target: any,
    asset_id: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  "get_balance(struct ContractId,struct ContractId)"(
    target: any,
    asset_id: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;
}
