name: 'Setup Rust env'

inputs:
  rust-version:
    description: 'Rust version'
    default: 1.64.0

runs:
  using: "composite"
  steps:
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ inputs.rust-version }}
        # selecting a toolchain either by action or manual `rustup` calls should happen
        # before the cache plugin, as it uses the current rustc version as its cache key
        override: true

    - uses: Swatinem/rust-cache@v1

    - name: Set git config
      run: |
        git config --global core.bigfilethreshold 100m
      shell:
        bash

    - uses: actions/checkout@v2
    - name: Install Fuel toolchain
      uses: FuelLabs/action-fuel-toolchain@master
      with:
        toolchain: beta-1