[project]
authors = ["Mohammad"]
entry = "main.sw"
license = "Apache-2.0"
name = "swayswap_contract"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "master" }
swayswap_abi = { path = "../swayswap_abi" }
