/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from 'fuels';
import { Interface, Contract } from 'fuels';
import type {
  ExchangeContractStorageSlots,
  ExchangeContractStorageSlotsInterface,
} from '../ExchangeContractStorageSlots';
const _abi = [
  {
    key: 'f383b0ce51358be57daa3b725fe44acdb2d880604e367199080b4379c41bb6ed',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
];

export class ExchangeContractStorageSlots__factory {
  static readonly abi = _abi;
  static createInterface(): ExchangeContractStorageSlotsInterface {
    return new Interface(_abi) as ExchangeContractStorageSlotsInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): ExchangeContractStorageSlots {
    return new Contract(id, _abi, walletOrProvider) as ExchangeContractStorageSlots;
  }
}
