/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { TokenContractAbi, TokenContractAbiInterface } from '../TokenContractAbi';
const _abi = [
  {
    type: 'function',
    inputs: [
      {
        name: 'mint_amount',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
      {
        name: 'address',
        type: 'struct Address',
        components: [
          {
            name: 'value',
            type: 'b256',
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: 'initialize',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'mint_amount',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
    ],
    name: 'set_mint_amount',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'mint_amount',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
    ],
    name: 'mint_coins',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'burn_amount',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
    ],
    name: 'burn_coins',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'coins',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
      {
        name: 'address',
        type: 'struct Address',
        components: [
          {
            name: 'value',
            type: 'b256',
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: 'transfer_coins',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'coins',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
      {
        name: 'asset_id',
        type: 'struct ContractId',
        components: [
          {
            name: 'value',
            type: 'b256',
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
      {
        name: 'address',
        type: 'struct Address',
        components: [
          {
            name: 'value',
            type: 'b256',
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: 'transfer_token_to_output',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'mint',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'get_mint_amount',
    outputs: [
      {
        name: '',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'get_balance',
    outputs: [
      {
        name: '',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'asset_id',
        type: 'struct ContractId',
        components: [
          {
            name: 'value',
            type: 'b256',
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: null,
      },
    ],
    name: 'get_token_balance',
    outputs: [
      {
        name: '',
        type: 'u64',
        components: null,
        typeArguments: null,
      },
    ],
  },
];

export class TokenContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): TokenContractAbiInterface {
    return new Interface(_abi) as TokenContractAbiInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): TokenContractAbi {
    return new Contract(id, _abi, walletOrProvider) as TokenContractAbi;
  }
}
