/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from 'fuels';
import { Interface, Contract } from 'fuels';
import type {
  TokenContractStorageSlots,
  TokenContractStorageSlotsInterface,
} from '../TokenContractStorageSlots';
const _abi = [
  {
    key: 'd625ff6d8e88efd7bb3476e748e5d5935618d78bfc7eedf584fe909ce0809fc3',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'de9090cb50e71c2588c773487d1da7066d0c719849a7e58dc8b6397a25c567c0',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
];

export class TokenContractStorageSlots__factory {
  static readonly abi = _abi;
  static createInterface(): TokenContractStorageSlotsInterface {
    return new Interface(_abi) as TokenContractStorageSlotsInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): TokenContractStorageSlots {
    return new Contract(id, _abi, walletOrProvider) as TokenContractStorageSlots;
  }
}
