/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet, AbstractAddress } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { TokenContractAbi, TokenContractAbiInterface } from '../TokenContractAbi';
const _abi = [
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      {
        type: 'u64',
        name: 'mint_amount',
      },
      {
        type: 'struct Address',
        name: 'address',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'set_mint_amount',
    inputs: [
      {
        type: 'u64',
        name: 'mint_amount',
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'mint_coins',
    inputs: [
      {
        type: 'u64',
        name: 'mint_amount',
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'burn_coins',
    inputs: [
      {
        type: 'u64',
        name: 'burn_amount',
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'transfer_coins',
    inputs: [
      {
        type: 'u64',
        name: 'coins',
      },
      {
        type: 'struct Address',
        name: 'address',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'transfer_token_to_output',
    inputs: [
      {
        type: 'u64',
        name: 'coins',
      },
      {
        type: 'struct ContractId',
        name: 'asset_id',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
      {
        type: 'struct Address',
        name: 'address',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'get_mint_amount',
    inputs: [],
    outputs: [
      {
        type: 'u64',
        name: '',
      },
    ],
  },
  {
    type: 'function',
    name: 'get_balance',
    inputs: [],
    outputs: [
      {
        type: 'u64',
        name: '',
      },
    ],
  },
  {
    type: 'function',
    name: 'get_token_balance',
    inputs: [
      {
        type: 'struct ContractId',
        name: 'asset_id',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
    outputs: [
      {
        type: 'u64',
        name: '',
      },
    ],
  },
];

export class TokenContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): TokenContractAbiInterface {
    return new Interface(_abi) as unknown as TokenContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: Wallet | Provider
  ): TokenContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as TokenContractAbi;
  }
}
