name: Setup forc toolchain

on:
  workflow_call:

env:
  RUST_VERSION: 1.61.0
  FORC_VERSION: 0.14.5

jobs:
  setup-forc:
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
        # selecting a toolchain either by action or manual `rustup` calls should happen
        # before the cache plugin, as it uses the current rustc version as its cache key
      - uses: Swatinem/rust-cache@v1

      - name: Set git config
        run: |
          git config --global core.bigfilethreshold 100m
      - name: Install Forc
        run: |
          curl -sSLf https://github.com/FuelLabs/sway/releases/download/v${{ env.FORC_VERSION }}/forc-binaries-linux_amd64.tar.gz -L -o forc.tar.gz
          tar -xvf forc.tar.gz
          chmod +x forc-binaries/forc
          mv forc-binaries/forc /usr/local/bin/forc

      # As contracts are really Heavy to build
      # and test we only test it when some
      # contract was updated on the PR
      - name: Change contracts
        id: changed-contracts
        uses: tj-actions/changed-files@v22.2
        with:
          files: |
            **/*.sw
            **/*.rs
            **/Cargo.toml
            **/Forc.toml